# Generated by Django 4.2.6 on 2023-11-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='montoMovimiento',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
