# Generated by Django 4.2.6 on 2023-11-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0003_alter_cuentabancaria_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='Cuentas.persona'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='Cuentas.cliente'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='Cuentas.cuentabancaria'),
        ),
    ]
